version: "3"
services:
  hub:
    image: dosel/zalenium
    logging:
      driver: "none"
    ports:
      - "4444:4444"
      - "5555:5555"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: >
      start --desiredContainers 2 
            --maxDockerSeleniumContainers 2 
            --maxTestSessions 3 
            --videoRecordingEnabled true

  profiling-module:
    image: sxiang/profiling
    depends_on:
      - hub
    environment:
      - HUB_HOST=hub
      - BROWSER=chrome
      - MODULE=profilingtest.xml
    volumes:
      - ./output/search-result:/usr/share/udemy/test-output
